In [ ]:
import torch

In [ ]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([ 62,  22, -15, -23, -68,  17])

In [ ]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [ ]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
input = torch.empty(2, 3)
input

tensor([[1.4769e-22, 4.3369e-41, 8.5498e-08],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [ ]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [ ]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [ ]:
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [ ]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
a = torch.empty((2, 3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[  8307560534635, 132920968554160,       879068832],
        [  8307560534645, 132920968554320,       879037584]])

In [ ]:
import torch
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [ ]:
%%time
start_time = time.time()

zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.00048494
CPU times: user 0 ns, sys: 921 µs, total: 921 µs
Wall time: 1.16 ms


In [ ]:
torch_rand1